trigger: 
- none

pool: 
  vmImage: "ubuntu-latest"

stages:
- stage: init_stage
  displayName: terraform stage
  jobs: 
  - job: deploy_job
    displayName: terraform job
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: terraform init
      inputs:
        provider: 'aws'
        command: 'init'
        backendServiceAWS: 'AWS terraform'
        backendAWSBucketName: 'terraform-4202'
        backendAWSKey: 'terraform-4202/state.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'plan'
        commandOptions: '-out=tfplan'
        environmentServiceNameAWS: 'AWS terraform'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'apply'
        commandOptions: 'tfplan -auto-approve'
        environmentServiceNameAWS: 'AWS terraform'
